---
name: rocs
version: 17.08.1
summary: Graph Theory Tool for Professors and Students.
description: Rocs is a Graph Theory IDE for designing and analyzing graph algorithms.
    It provides an easy to use visual editor for creating graphs, a scripting engine
    to execute algorithms, and several helper tools for simulations and experiments.
    Algorithms are specified in JavaScript.
confinement: strict
grade: stable
apps:
    rocs:
        command: kf5-launch rocs
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.rocs
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    rocs:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libboost-dev
        - libboost-graph-dev
        - libgrantlee5-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/rocs-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
