#!/bin/sh

export LANG=C.UTF-8
export LC_ALL=C.UTF-8

xvfb-run -a --server-args="-screen 0 1024x768x24" \
    Xephyr -reset -br -screen 1024x768 :2 & x_pid=$!

trap "kill ${x_pid}" EXIT

DISPLAY=:2 dbus-run-session -- dh_auto_test
